module.exports={
    HOST:"jFRxw82nl6ye0JqNTmQF",
    USER:"root",
    PASSWORD:"jFRxw82nl6ye0JqNTmQF",
    DB:"railway",
    dailect:"mysql",
    pool:{
        max:5,
        min:0,
        acquire:30000,
        idle:10000
    }
}